# Generated by Django 3.1.3 on 2021-01-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Distance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
